# Generated by Django 4.2 on 2023-11-14 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='users',
        ),
        migrations.AddField(
            model_name='dashboard',
            name='clients',
            field=models.ManyToManyField(to='web_app.client', verbose_name='Clientes'),
        ),
    ]
