# Generated by Django 4.0.2 on 2023-11-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('web_app', '0002_remove_dashboard_users_dashboard_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='clientuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='clients',
            field=models.ManyToManyField(to='web_app.Client', verbose_name='Clientes'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='tags',
            field=models.ManyToManyField(to='web_app.DashboardTag', verbose_name='Etiquetas'),
        ),
    ]
